ALTER TABLE ideas ADD COLUMN stage_image TEXT NOT NULL DEFAULT '';
ALTER TABLE ideas ADD COLUMN monster_image TEXT NOT NULL DEFAULT '';
ALTER TABLE ideas ADD COLUMN mission_image TEXT NOT NULL DEFAULT '';
